import { translations, type Locale } from '../i18n/translations'
import type { Patient } from '../types/patient'
import { formatDate } from './format'

function getPdfLocale(): Locale {
  const stored = localStorage.getItem('alcacrea-locale') as Locale | null
  return stored === 'en' ? 'en' : 'fr'
}

export function generatePatientsPdf(patients: Patient[], filename?: string) {
  const locale = getPdfLocale()
  const t = translations[locale]
  const date = new Date().toISOString().slice(0, 10)

  const rows = patients.flatMap((p) =>
    p.exams.map((e) => ({
      patient: `${p.prenom} ${p.nom}`,
      type: t.examType[e.type],
      date: formatDate(e.date, locale),
      severity: t.severity[e.severity],
      iah: e.metrics.iah ?? '—',
      satO2: e.metrics.satO2Min ?? '—',
      vems: e.metrics.vems ?? '—',
      cvf: e.metrics.cvf ?? '—',
    })),
  )

  const tableRows = rows
    .map(
      (r) => `
      <tr>
        <td>${r.patient}</td>
        <td>${r.type}</td>
        <td>${r.date}</td>
        <td>${r.severity}</td>
        <td>${r.iah}</td>
        <td>${r.satO2}</td>
        <td>${r.vems}</td>
        <td>${r.cvf}</td>
      </tr>`,
    )
    .join('')

  const title = locale === 'fr' ? 'Rapport des examens' : 'Exam report'
  const generated = locale === 'fr' ? 'Généré le' : 'Generated on'
  const footer = locale === 'fr'
    ? 'Document généré par Alcacrea — usage clinique interne'
    : 'Document generated by Alcacrea — internal clinical use'
  const patientsLabel = locale === 'fr' ? 'patients' : 'patients'
  const examsLabel = locale === 'fr' ? 'examens' : 'exams'

  const html = `<!DOCTYPE html>
<html lang="${locale}">
<head>
  <meta charset="UTF-8" />
  <title>Alcacrea — ${title}</title>
  <style>
    @page { margin: 18mm; }
    body { font-family: Georgia, serif; color: #524e48; margin: 0; padding: 24px; background: #ede8e1; }
    h1 { font-size: 22px; font-weight: normal; margin: 0 0 4px; }
    .meta { font-family: monospace; font-size: 10px; color: #7ab5ae; letter-spacing: 0.12em; text-transform: uppercase; margin-bottom: 20px; }
    .stats { display: flex; gap: 24px; margin-bottom: 24px; font-size: 13px; }
    .stats span { font-family: monospace; }
    table { width: 100%; border-collapse: collapse; font-size: 11px; }
    th { text-align: left; padding: 8px 6px; border-bottom: 2px solid #7ab5ae; font-family: monospace; font-size: 9px; text-transform: uppercase; letter-spacing: 0.08em; color: #7ab5ae; }
    td { padding: 7px 6px; border-bottom: 1px solid #e4ddd4; }
    tr:nth-child(even) td { background: #f3efe8; }
    .footer { margin-top: 28px; font-size: 9px; color: #aaa; font-family: monospace; }
  </style>
</head>
<body>
  <p class="meta">${t.brand.clinicFooter}</p>
  <h1>${title}</h1>
  <div class="stats">
    <span>${patients.length} ${patientsLabel}</span>
    <span>${rows.length} ${examsLabel}</span>
    <span>${generated} ${formatDate(date, locale)}</span>
  </div>
  <table>
    <thead>
      <tr>
        <th>${t.export.colPatient}</th><th>${t.export.colExam}</th><th>${t.export.colDate}</th><th>${t.export.colSeverity}</th>
        <th>${t.export.colIah}</th><th>${t.export.colSatO2}</th><th>${t.metrics.vems}</th><th>${t.metrics.cvf}</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
  </table>
  <p class="footer">${footer}</p>
  <script>window.onload = () => { window.print(); }</script>
</body>
</html>`

  const name = filename ?? `alcacrea-rapport-${date}.pdf`
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const win = window.open(url, '_blank')
  if (!win) {
    const a = document.createElement('a')
    a.href = url
    a.download = name.replace('.pdf', '.html')
    a.click()
  }
  setTimeout(() => URL.revokeObjectURL(url), 60_000)
}
