import { translations, type Locale } from '../i18n/translations'
import type { Patient } from '../types/patient'
import { formatDate } from './format'
import { buildPdfBlob, downloadPdfBlob } from './pdfDocument'

function getPdfLocale(): Locale {
  const stored = localStorage.getItem('alcacrea-locale') as Locale | null
  return stored === 'en' ? 'en' : 'fr'
}

function patientSlug(patient: Patient): string {
  const base = `${patient.nom}-${patient.prenom}`.toLowerCase().replace(/[^a-z0-9]+/g, '-')
  return base.replace(/^-|-$/g, '') || 'patient'
}

export function generatePatientsPdf(patients: Patient[], filename?: string) {
  const locale = getPdfLocale()
  const t = translations[locale]
  const date = new Date().toISOString().slice(0, 10)

  const empty = '-'

  const rows = patients.flatMap((p) =>
    p.exams.map((e) => [
      `${p.prenom} ${p.nom}`.trim(),
      t.examType[e.type],
      formatDate(e.date, locale),
      t.severity[e.severity],
      e.metrics.iah != null ? String(e.metrics.iah) : empty,
      e.metrics.satO2Min != null ? String(e.metrics.satO2Min) : empty,
      e.metrics.vems != null ? String(e.metrics.vems) : empty,
      e.metrics.cvf != null ? String(e.metrics.cvf) : empty,
    ]),
  )

  const title = locale === 'fr' ? 'Rapport des examens' : 'Exam report'
  const generated = locale === 'fr' ? 'Généré le' : 'Generated on'
  const footer =
    locale === 'fr'
      ? 'Document généré par Alcacrea — usage clinique interne'
      : 'Document generated by Alcacrea — internal clinical use'
  const patientsLabel = locale === 'fr' ? 'patients' : 'patients'
  const examsLabel = locale === 'fr' ? 'examens' : 'exams'

  const defaultName =
    patients.length === 1
      ? `alcacrea-${patientSlug(patients[0])}-${date}.pdf`
      : `alcacrea-rapport-${date}.pdf`

  const blob = buildPdfBlob({
    title,
    subtitle: `${patients.length} ${patientsLabel} · ${rows.length} ${examsLabel} · ${generated} ${formatDate(date, locale)}`,
    footer,
    columns: [
      { header: t.export.colPatient, width: 118, maxChars: 22 },
      { header: t.export.colExam, width: 78, maxChars: 14 },
      { header: t.export.colDate, width: 68, maxChars: 12 },
      { header: t.export.colSeverity, width: 52, maxChars: 10 },
      { header: t.export.colIah, width: 38, maxChars: 6 },
      { header: 'SpO2', width: 38, maxChars: 6 },
      { header: t.metrics.vems, width: 38, maxChars: 6 },
      { header: t.metrics.cvf, width: 38, maxChars: 6 },
    ],
    rows,
  })

  downloadPdfBlob(blob, filename ?? defaultName)
}
